### ISSUE TITLE
requirments

### ISSUE THREAD

**Issue by mostaf7583** [AhmedAshrafAZ/cms-downloader#12]
![image](https://user-images.githubusercontent.com/73074293/137479061-0cc226b1-ae23-48d8-b82f-8e98fb073b60.png)
as you see in the photo  the requirements .txt is not working correctly   so to install i installed every library independently

**Comment by AhmedAshrafAZ** [comment]
I found a solution, tried it and it worked!
Just try to download [Windows Subsystem for Linux  (wsl)](https://docs.microsoft.com/en-us/windows/wsl/install). Then you can run the Linux commands inside your windows environment.
