### ISSUE TITLE
Special characters in course name

### ISSUE THREAD

**Issue by ssary** [AhmedAshrafAZ/cms-downloader#13]
If the course name contains ':' , '/' ,'<' , '>' and '|' it will not execute mkdir i tried to solve it in getcontent() and in getSeason() courseName to replace these special chars global but it didn't work and tells me:
Error: ENOENT: no such file or directory, mkdir '.\cms_downloads\Winter 2021\Mathematics III: Calculus II\week 2021-10-23'
it'll be great to fix this one or to tell me where to fix it.
thanks

**Comment by AhmedAshrafAZ** [comment]
Hello @Ssary,
I've tried it and it is working fine with me, it might be a problem with the content name not the course name. So, can you please send me a screenshot for the full logs?
You can contact me on [Facebook](https://fb.com/AhmedAshrafAZ/) for easier communication.
