### ISSUE TITLE
error while downloading

### ISSUE THREAD

**Issue by AbdalrahmanHafez** [AhmedAshrafAZ/cms-downloader#8]
![image](https://user-images.githubusercontent.com/10910517/104136418-9b472000-539e-11eb-9de2-b9386d775e70.png)

**Comment by aboueleyes** [comment]
This can be solved by getting the m3u8 file from the network response 
[Puppeteer can get you the log so you can search in the response for the m3u8 link and download it](https://stackoverflow.com/questions/52969381/how-can-i-capture-all-network-requests-and-full-response-data-when-loading-a-pag)
in case  of failure of download:
1. open that video 
2. get m3u8 link and download it 
[I've implemented in py ](https://github.com/aboueleyes/cms-scrapper)
@AhmedAshrafAZ

**Comment by AhmedAshrafAZ** [comment]
@aboueleyes 
I will fix it insha'Allah and add some things as soon as I finish my finals; because currently I don't have that kind of spare time to fix it :")

And, Thank You for a lot of things 🙌🏻.
